//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobie_store.DeleteService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DeleteService.IDeleteService")]
    public interface IDeleteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteService/Delete_admin", ReplyAction="http://tempuri.org/IDeleteService/Delete_adminResponse")]
        string Delete_admin(string token, int admin_id, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteService/Delete_admin", ReplyAction="http://tempuri.org/IDeleteService/Delete_adminResponse")]
        System.Threading.Tasks.Task<string> Delete_adminAsync(string token, int admin_id, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteService/Delete_category", ReplyAction="http://tempuri.org/IDeleteService/Delete_categoryResponse")]
        string Delete_category(string token, int admin_id, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteService/Delete_category", ReplyAction="http://tempuri.org/IDeleteService/Delete_categoryResponse")]
        System.Threading.Tasks.Task<string> Delete_categoryAsync(string token, int admin_id, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteService/Delete_comment", ReplyAction="http://tempuri.org/IDeleteService/Delete_commentResponse")]
        string Delete_comment(string utoken, int user_id, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteService/Delete_comment", ReplyAction="http://tempuri.org/IDeleteService/Delete_commentResponse")]
        System.Threading.Tasks.Task<string> Delete_commentAsync(string utoken, int user_id, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteService/Delete_discount", ReplyAction="http://tempuri.org/IDeleteService/Delete_discountResponse")]
        string Delete_discount(string token, int admin_id, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteService/Delete_discount", ReplyAction="http://tempuri.org/IDeleteService/Delete_discountResponse")]
        System.Threading.Tasks.Task<string> Delete_discountAsync(string token, int admin_id, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteService/Delete_image", ReplyAction="http://tempuri.org/IDeleteService/Delete_imageResponse")]
        string Delete_image(string token, int admin_id, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteService/Delete_image", ReplyAction="http://tempuri.org/IDeleteService/Delete_imageResponse")]
        System.Threading.Tasks.Task<string> Delete_imageAsync(string token, int admin_id, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteService/Delete_order", ReplyAction="http://tempuri.org/IDeleteService/Delete_orderResponse")]
        string Delete_order(string utoken, int user_id, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteService/Delete_order", ReplyAction="http://tempuri.org/IDeleteService/Delete_orderResponse")]
        System.Threading.Tasks.Task<string> Delete_orderAsync(string utoken, int user_id, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteService/Delete_post", ReplyAction="http://tempuri.org/IDeleteService/Delete_postResponse")]
        string Delete_post(string token, int admin_id, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteService/Delete_post", ReplyAction="http://tempuri.org/IDeleteService/Delete_postResponse")]
        System.Threading.Tasks.Task<string> Delete_postAsync(string token, int admin_id, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteService/Delete_product", ReplyAction="http://tempuri.org/IDeleteService/Delete_productResponse")]
        string Delete_product(string token, int admin_id, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteService/Delete_product", ReplyAction="http://tempuri.org/IDeleteService/Delete_productResponse")]
        System.Threading.Tasks.Task<string> Delete_productAsync(string token, int admin_id, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteService/Delete_review", ReplyAction="http://tempuri.org/IDeleteService/Delete_reviewResponse")]
        string Delete_review(string utoken, int user_id, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteService/Delete_review", ReplyAction="http://tempuri.org/IDeleteService/Delete_reviewResponse")]
        System.Threading.Tasks.Task<string> Delete_reviewAsync(string utoken, int user_id, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteService/Delete_user", ReplyAction="http://tempuri.org/IDeleteService/Delete_userResponse")]
        string Delete_user(string utoken, int user_id, System.Nullable<int> admin_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteService/Delete_user", ReplyAction="http://tempuri.org/IDeleteService/Delete_userResponse")]
        System.Threading.Tasks.Task<string> Delete_userAsync(string utoken, int user_id, System.Nullable<int> admin_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteService/Delete_token", ReplyAction="http://tempuri.org/IDeleteService/Delete_tokenResponse")]
        string Delete_token(string utoken, int user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteService/Delete_token", ReplyAction="http://tempuri.org/IDeleteService/Delete_tokenResponse")]
        System.Threading.Tasks.Task<string> Delete_tokenAsync(string utoken, int user_id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeleteServiceChannel : Mobie_store.DeleteService.IDeleteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteServiceClient : System.ServiceModel.ClientBase<Mobie_store.DeleteService.IDeleteService>, Mobie_store.DeleteService.IDeleteService {
        
        public DeleteServiceClient() {
        }
        
        public DeleteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeleteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeleteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeleteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Delete_admin(string token, int admin_id, int id) {
            return base.Channel.Delete_admin(token, admin_id, id);
        }
        
        public System.Threading.Tasks.Task<string> Delete_adminAsync(string token, int admin_id, int id) {
            return base.Channel.Delete_adminAsync(token, admin_id, id);
        }
        
        public string Delete_category(string token, int admin_id, int id) {
            return base.Channel.Delete_category(token, admin_id, id);
        }
        
        public System.Threading.Tasks.Task<string> Delete_categoryAsync(string token, int admin_id, int id) {
            return base.Channel.Delete_categoryAsync(token, admin_id, id);
        }
        
        public string Delete_comment(string utoken, int user_id, int id) {
            return base.Channel.Delete_comment(utoken, user_id, id);
        }
        
        public System.Threading.Tasks.Task<string> Delete_commentAsync(string utoken, int user_id, int id) {
            return base.Channel.Delete_commentAsync(utoken, user_id, id);
        }
        
        public string Delete_discount(string token, int admin_id, int id) {
            return base.Channel.Delete_discount(token, admin_id, id);
        }
        
        public System.Threading.Tasks.Task<string> Delete_discountAsync(string token, int admin_id, int id) {
            return base.Channel.Delete_discountAsync(token, admin_id, id);
        }
        
        public string Delete_image(string token, int admin_id, int id) {
            return base.Channel.Delete_image(token, admin_id, id);
        }
        
        public System.Threading.Tasks.Task<string> Delete_imageAsync(string token, int admin_id, int id) {
            return base.Channel.Delete_imageAsync(token, admin_id, id);
        }
        
        public string Delete_order(string utoken, int user_id, int id) {
            return base.Channel.Delete_order(utoken, user_id, id);
        }
        
        public System.Threading.Tasks.Task<string> Delete_orderAsync(string utoken, int user_id, int id) {
            return base.Channel.Delete_orderAsync(utoken, user_id, id);
        }
        
        public string Delete_post(string token, int admin_id, int id) {
            return base.Channel.Delete_post(token, admin_id, id);
        }
        
        public System.Threading.Tasks.Task<string> Delete_postAsync(string token, int admin_id, int id) {
            return base.Channel.Delete_postAsync(token, admin_id, id);
        }
        
        public string Delete_product(string token, int admin_id, int id) {
            return base.Channel.Delete_product(token, admin_id, id);
        }
        
        public System.Threading.Tasks.Task<string> Delete_productAsync(string token, int admin_id, int id) {
            return base.Channel.Delete_productAsync(token, admin_id, id);
        }
        
        public string Delete_review(string utoken, int user_id, int id) {
            return base.Channel.Delete_review(utoken, user_id, id);
        }
        
        public System.Threading.Tasks.Task<string> Delete_reviewAsync(string utoken, int user_id, int id) {
            return base.Channel.Delete_reviewAsync(utoken, user_id, id);
        }
        
        public string Delete_user(string utoken, int user_id, System.Nullable<int> admin_id) {
            return base.Channel.Delete_user(utoken, user_id, admin_id);
        }
        
        public System.Threading.Tasks.Task<string> Delete_userAsync(string utoken, int user_id, System.Nullable<int> admin_id) {
            return base.Channel.Delete_userAsync(utoken, user_id, admin_id);
        }
        
        public string Delete_token(string utoken, int user_id) {
            return base.Channel.Delete_token(utoken, user_id);
        }
        
        public System.Threading.Tasks.Task<string> Delete_tokenAsync(string utoken, int user_id) {
            return base.Channel.Delete_tokenAsync(utoken, user_id);
        }
    }
}
