//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobie_store.ViewService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="admin", Namespace="http://schemas.datacontract.org/2004/07/MyWCFService.Models")]
    [System.SerializableAttribute()]
    public partial class admin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fullnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> levelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pwdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fullname {
            get {
                return this.fullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.fullnameField, value) != true)) {
                    this.fullnameField = value;
                    this.RaisePropertyChanged("fullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> level {
            get {
                return this.levelField;
            }
            set {
                if ((this.levelField.Equals(value) != true)) {
                    this.levelField = value;
                    this.RaisePropertyChanged("level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pwd {
            get {
                return this.pwdField;
            }
            set {
                if ((object.ReferenceEquals(this.pwdField, value) != true)) {
                    this.pwdField = value;
                    this.RaisePropertyChanged("pwd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="category", Namespace="http://schemas.datacontract.org/2004/07/MyWCFService.Models")]
    [System.SerializableAttribute()]
    public partial class category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="comment", Namespace="http://schemas.datacontract.org/2004/07/MyWCFService.Models")]
    [System.SerializableAttribute()]
    public partial class comment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> product_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> users_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comments {
            get {
                return this.commentsField;
            }
            set {
                if ((object.ReferenceEquals(this.commentsField, value) != true)) {
                    this.commentsField = value;
                    this.RaisePropertyChanged("comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> product_id {
            get {
                return this.product_idField;
            }
            set {
                if ((this.product_idField.Equals(value) != true)) {
                    this.product_idField = value;
                    this.RaisePropertyChanged("product_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> users_id {
            get {
                return this.users_idField;
            }
            set {
                if ((this.users_idField.Equals(value) != true)) {
                    this.users_idField = value;
                    this.RaisePropertyChanged("users_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="discount", Namespace="http://schemas.datacontract.org/2004/07/MyWCFService.Models")]
    [System.SerializableAttribute()]
    public partial class discount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="image", Namespace="http://schemas.datacontract.org/2004/07/MyWCFService.Models")]
    [System.SerializableAttribute()]
    public partial class image : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> product_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> product_id {
            get {
                return this.product_idField;
            }
            set {
                if ((this.product_idField.Equals(value) != true)) {
                    this.product_idField = value;
                    this.RaisePropertyChanged("product_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                if ((object.ReferenceEquals(this.urlField, value) != true)) {
                    this.urlField = value;
                    this.RaisePropertyChanged("url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="order", Namespace="http://schemas.datacontract.org/2004/07/MyWCFService.Models")]
    [System.SerializableAttribute()]
    public partial class order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_createField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string methodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string total_moneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> users_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_create {
            get {
                return this.date_createField;
            }
            set {
                if ((this.date_createField.Equals(value) != true)) {
                    this.date_createField = value;
                    this.RaisePropertyChanged("date_create");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string method {
            get {
                return this.methodField;
            }
            set {
                if ((object.ReferenceEquals(this.methodField, value) != true)) {
                    this.methodField = value;
                    this.RaisePropertyChanged("method");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string total_money {
            get {
                return this.total_moneyField;
            }
            set {
                if ((object.ReferenceEquals(this.total_moneyField, value) != true)) {
                    this.total_moneyField = value;
                    this.RaisePropertyChanged("total_money");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> users_id {
            get {
                return this.users_idField;
            }
            set {
                if ((this.users_idField.Equals(value) != true)) {
                    this.users_idField = value;
                    this.RaisePropertyChanged("users_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="post", Namespace="http://schemas.datacontract.org/2004/07/MyWCFService.Models")]
    [System.SerializableAttribute()]
    public partial class post : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> product_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripton {
            get {
                return this.descriptonField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptonField, value) != true)) {
                    this.descriptonField = value;
                    this.RaisePropertyChanged("descripton");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> product_id {
            get {
                return this.product_idField;
            }
            set {
                if ((this.product_idField.Equals(value) != true)) {
                    this.product_idField = value;
                    this.RaisePropertyChanged("product_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="product", Namespace="http://schemas.datacontract.org/2004/07/MyWCFService.Models")]
    [System.SerializableAttribute()]
    public partial class product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GhzField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> activateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string batteryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string camera_frontField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string camera_rearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string colorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> discount_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string displayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> followField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> product_cate_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ramField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sensorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string simField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string skuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string storageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ghz {
            get {
                return this.GhzField;
            }
            set {
                if ((object.ReferenceEquals(this.GhzField, value) != true)) {
                    this.GhzField = value;
                    this.RaisePropertyChanged("Ghz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> activate {
            get {
                return this.activateField;
            }
            set {
                if ((this.activateField.Equals(value) != true)) {
                    this.activateField = value;
                    this.RaisePropertyChanged("activate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string battery {
            get {
                return this.batteryField;
            }
            set {
                if ((object.ReferenceEquals(this.batteryField, value) != true)) {
                    this.batteryField = value;
                    this.RaisePropertyChanged("battery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string camera_front {
            get {
                return this.camera_frontField;
            }
            set {
                if ((object.ReferenceEquals(this.camera_frontField, value) != true)) {
                    this.camera_frontField = value;
                    this.RaisePropertyChanged("camera_front");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string camera_rear {
            get {
                return this.camera_rearField;
            }
            set {
                if ((object.ReferenceEquals(this.camera_rearField, value) != true)) {
                    this.camera_rearField = value;
                    this.RaisePropertyChanged("camera_rear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string color {
            get {
                return this.colorField;
            }
            set {
                if ((object.ReferenceEquals(this.colorField, value) != true)) {
                    this.colorField = value;
                    this.RaisePropertyChanged("color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cpu {
            get {
                return this.cpuField;
            }
            set {
                if ((object.ReferenceEquals(this.cpuField, value) != true)) {
                    this.cpuField = value;
                    this.RaisePropertyChanged("cpu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> discount_id {
            get {
                return this.discount_idField;
            }
            set {
                if ((this.discount_idField.Equals(value) != true)) {
                    this.discount_idField = value;
                    this.RaisePropertyChanged("discount_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string display {
            get {
                return this.displayField;
            }
            set {
                if ((object.ReferenceEquals(this.displayField, value) != true)) {
                    this.displayField = value;
                    this.RaisePropertyChanged("display");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> follow {
            get {
                return this.followField;
            }
            set {
                if ((this.followField.Equals(value) != true)) {
                    this.followField = value;
                    this.RaisePropertyChanged("follow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string price {
            get {
                return this.priceField;
            }
            set {
                if ((object.ReferenceEquals(this.priceField, value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> product_cate_id {
            get {
                return this.product_cate_idField;
            }
            set {
                if ((this.product_cate_idField.Equals(value) != true)) {
                    this.product_cate_idField = value;
                    this.RaisePropertyChanged("product_cate_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ram {
            get {
                return this.ramField;
            }
            set {
                if ((object.ReferenceEquals(this.ramField, value) != true)) {
                    this.ramField = value;
                    this.RaisePropertyChanged("ram");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sensor {
            get {
                return this.sensorField;
            }
            set {
                if ((object.ReferenceEquals(this.sensorField, value) != true)) {
                    this.sensorField = value;
                    this.RaisePropertyChanged("sensor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sim {
            get {
                return this.simField;
            }
            set {
                if ((object.ReferenceEquals(this.simField, value) != true)) {
                    this.simField = value;
                    this.RaisePropertyChanged("sim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sku {
            get {
                return this.skuField;
            }
            set {
                if ((object.ReferenceEquals(this.skuField, value) != true)) {
                    this.skuField = value;
                    this.RaisePropertyChanged("sku");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string storage {
            get {
                return this.storageField;
            }
            set {
                if ((object.ReferenceEquals(this.storageField, value) != true)) {
                    this.storageField = value;
                    this.RaisePropertyChanged("storage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="review", Namespace="http://schemas.datacontract.org/2004/07/MyWCFService.Models")]
    [System.SerializableAttribute()]
    public partial class review : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> product_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> users_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> product_id {
            get {
                return this.product_idField;
            }
            set {
                if ((this.product_idField.Equals(value) != true)) {
                    this.product_idField = value;
                    this.RaisePropertyChanged("product_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reviews {
            get {
                return this.reviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.reviewsField, value) != true)) {
                    this.reviewsField = value;
                    this.RaisePropertyChanged("reviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> users_id {
            get {
                return this.users_idField;
            }
            set {
                if ((this.users_idField.Equals(value) != true)) {
                    this.users_idField = value;
                    this.RaisePropertyChanged("users_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="user", Namespace="http://schemas.datacontract.org/2004/07/MyWCFService.Models")]
    [System.SerializableAttribute()]
    public partial class user : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> activatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fullnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pwdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> activated {
            get {
                return this.activatedField;
            }
            set {
                if ((this.activatedField.Equals(value) != true)) {
                    this.activatedField = value;
                    this.RaisePropertyChanged("activated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fullname {
            get {
                return this.fullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.fullnameField, value) != true)) {
                    this.fullnameField = value;
                    this.RaisePropertyChanged("fullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pwd {
            get {
                return this.pwdField;
            }
            set {
                if ((object.ReferenceEquals(this.pwdField, value) != true)) {
                    this.pwdField = value;
                    this.RaisePropertyChanged("pwd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="token", Namespace="http://schemas.datacontract.org/2004/07/MyWCFService.Models")]
    [System.SerializableAttribute()]
    public partial class token : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> admin_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> admin_id {
            get {
                return this.admin_idField;
            }
            set {
                if ((this.admin_idField.Equals(value) != true)) {
                    this.admin_idField = value;
                    this.RaisePropertyChanged("admin_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="utoken", Namespace="http://schemas.datacontract.org/2004/07/MyWCFService.Models")]
    [System.SerializableAttribute()]
    public partial class utoken : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> user_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((this.user_idField.Equals(value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ViewService.IViewService")]
    public interface IViewService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_admin", ReplyAction="http://tempuri.org/IViewService/Get_adminResponse")]
        Mobie_store.ViewService.admin[] Get_admin(string token, int admin_id, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_admin", ReplyAction="http://tempuri.org/IViewService/Get_adminResponse")]
        System.Threading.Tasks.Task<Mobie_store.ViewService.admin[]> Get_adminAsync(string token, int admin_id, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_category", ReplyAction="http://tempuri.org/IViewService/Get_categoryResponse")]
        Mobie_store.ViewService.category[] Get_category(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_category", ReplyAction="http://tempuri.org/IViewService/Get_categoryResponse")]
        System.Threading.Tasks.Task<Mobie_store.ViewService.category[]> Get_categoryAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_comment", ReplyAction="http://tempuri.org/IViewService/Get_commentResponse")]
        Mobie_store.ViewService.comment[] Get_comment(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_comment", ReplyAction="http://tempuri.org/IViewService/Get_commentResponse")]
        System.Threading.Tasks.Task<Mobie_store.ViewService.comment[]> Get_commentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_discount", ReplyAction="http://tempuri.org/IViewService/Get_discountResponse")]
        Mobie_store.ViewService.discount[] Get_discount(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_discount", ReplyAction="http://tempuri.org/IViewService/Get_discountResponse")]
        System.Threading.Tasks.Task<Mobie_store.ViewService.discount[]> Get_discountAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_image", ReplyAction="http://tempuri.org/IViewService/Get_imageResponse")]
        Mobie_store.ViewService.image[] Get_image(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_image", ReplyAction="http://tempuri.org/IViewService/Get_imageResponse")]
        System.Threading.Tasks.Task<Mobie_store.ViewService.image[]> Get_imageAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_order", ReplyAction="http://tempuri.org/IViewService/Get_orderResponse")]
        Mobie_store.ViewService.order[] Get_order(string utoken, int id, System.Nullable<int> user_id, System.Nullable<int> admin_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_order", ReplyAction="http://tempuri.org/IViewService/Get_orderResponse")]
        System.Threading.Tasks.Task<Mobie_store.ViewService.order[]> Get_orderAsync(string utoken, int id, System.Nullable<int> user_id, System.Nullable<int> admin_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_post", ReplyAction="http://tempuri.org/IViewService/Get_postResponse")]
        Mobie_store.ViewService.post[] Get_post(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_post", ReplyAction="http://tempuri.org/IViewService/Get_postResponse")]
        System.Threading.Tasks.Task<Mobie_store.ViewService.post[]> Get_postAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_product", ReplyAction="http://tempuri.org/IViewService/Get_productResponse")]
        Mobie_store.ViewService.product[] Get_product(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_product", ReplyAction="http://tempuri.org/IViewService/Get_productResponse")]
        System.Threading.Tasks.Task<Mobie_store.ViewService.product[]> Get_productAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_review", ReplyAction="http://tempuri.org/IViewService/Get_reviewResponse")]
        Mobie_store.ViewService.review[] Get_review(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_review", ReplyAction="http://tempuri.org/IViewService/Get_reviewResponse")]
        System.Threading.Tasks.Task<Mobie_store.ViewService.review[]> Get_reviewAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_user", ReplyAction="http://tempuri.org/IViewService/Get_userResponse")]
        Mobie_store.ViewService.user[] Get_user(string utoken, int id, System.Nullable<int> admin_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_user", ReplyAction="http://tempuri.org/IViewService/Get_userResponse")]
        System.Threading.Tasks.Task<Mobie_store.ViewService.user[]> Get_userAsync(string utoken, int id, System.Nullable<int> admin_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_token", ReplyAction="http://tempuri.org/IViewService/Get_tokenResponse")]
        Mobie_store.ViewService.token[] Get_token(string token, int admin_id, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_token", ReplyAction="http://tempuri.org/IViewService/Get_tokenResponse")]
        System.Threading.Tasks.Task<Mobie_store.ViewService.token[]> Get_tokenAsync(string token, int admin_id, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_utoken", ReplyAction="http://tempuri.org/IViewService/Get_utokenResponse")]
        Mobie_store.ViewService.utoken[] Get_utoken(string utoken, int user_id, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewService/Get_utoken", ReplyAction="http://tempuri.org/IViewService/Get_utokenResponse")]
        System.Threading.Tasks.Task<Mobie_store.ViewService.utoken[]> Get_utokenAsync(string utoken, int user_id, int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IViewServiceChannel : Mobie_store.ViewService.IViewService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ViewServiceClient : System.ServiceModel.ClientBase<Mobie_store.ViewService.IViewService>, Mobie_store.ViewService.IViewService {
        
        public ViewServiceClient() {
        }
        
        public ViewServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ViewServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViewServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViewServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Mobie_store.ViewService.admin[] Get_admin(string token, int admin_id, int id) {
            return base.Channel.Get_admin(token, admin_id, id);
        }
        
        public System.Threading.Tasks.Task<Mobie_store.ViewService.admin[]> Get_adminAsync(string token, int admin_id, int id) {
            return base.Channel.Get_adminAsync(token, admin_id, id);
        }
        
        public Mobie_store.ViewService.category[] Get_category(int id) {
            return base.Channel.Get_category(id);
        }
        
        public System.Threading.Tasks.Task<Mobie_store.ViewService.category[]> Get_categoryAsync(int id) {
            return base.Channel.Get_categoryAsync(id);
        }
        
        public Mobie_store.ViewService.comment[] Get_comment(int id) {
            return base.Channel.Get_comment(id);
        }
        
        public System.Threading.Tasks.Task<Mobie_store.ViewService.comment[]> Get_commentAsync(int id) {
            return base.Channel.Get_commentAsync(id);
        }
        
        public Mobie_store.ViewService.discount[] Get_discount(int id) {
            return base.Channel.Get_discount(id);
        }
        
        public System.Threading.Tasks.Task<Mobie_store.ViewService.discount[]> Get_discountAsync(int id) {
            return base.Channel.Get_discountAsync(id);
        }
        
        public Mobie_store.ViewService.image[] Get_image(int id) {
            return base.Channel.Get_image(id);
        }
        
        public System.Threading.Tasks.Task<Mobie_store.ViewService.image[]> Get_imageAsync(int id) {
            return base.Channel.Get_imageAsync(id);
        }
        
        public Mobie_store.ViewService.order[] Get_order(string utoken, int id, System.Nullable<int> user_id, System.Nullable<int> admin_id) {
            return base.Channel.Get_order(utoken, id, user_id, admin_id);
        }
        
        public System.Threading.Tasks.Task<Mobie_store.ViewService.order[]> Get_orderAsync(string utoken, int id, System.Nullable<int> user_id, System.Nullable<int> admin_id) {
            return base.Channel.Get_orderAsync(utoken, id, user_id, admin_id);
        }
        
        public Mobie_store.ViewService.post[] Get_post(int id) {
            return base.Channel.Get_post(id);
        }
        
        public System.Threading.Tasks.Task<Mobie_store.ViewService.post[]> Get_postAsync(int id) {
            return base.Channel.Get_postAsync(id);
        }
        
        public Mobie_store.ViewService.product[] Get_product(int id) {
            return base.Channel.Get_product(id);
        }
        
        public System.Threading.Tasks.Task<Mobie_store.ViewService.product[]> Get_productAsync(int id) {
            return base.Channel.Get_productAsync(id);
        }
        
        public Mobie_store.ViewService.review[] Get_review(int id) {
            return base.Channel.Get_review(id);
        }
        
        public System.Threading.Tasks.Task<Mobie_store.ViewService.review[]> Get_reviewAsync(int id) {
            return base.Channel.Get_reviewAsync(id);
        }
        
        public Mobie_store.ViewService.user[] Get_user(string utoken, int id, System.Nullable<int> admin_id) {
            return base.Channel.Get_user(utoken, id, admin_id);
        }
        
        public System.Threading.Tasks.Task<Mobie_store.ViewService.user[]> Get_userAsync(string utoken, int id, System.Nullable<int> admin_id) {
            return base.Channel.Get_userAsync(utoken, id, admin_id);
        }
        
        public Mobie_store.ViewService.token[] Get_token(string token, int admin_id, int id) {
            return base.Channel.Get_token(token, admin_id, id);
        }
        
        public System.Threading.Tasks.Task<Mobie_store.ViewService.token[]> Get_tokenAsync(string token, int admin_id, int id) {
            return base.Channel.Get_tokenAsync(token, admin_id, id);
        }
        
        public Mobie_store.ViewService.utoken[] Get_utoken(string utoken, int user_id, int id) {
            return base.Channel.Get_utoken(utoken, user_id, id);
        }
        
        public System.Threading.Tasks.Task<Mobie_store.ViewService.utoken[]> Get_utokenAsync(string utoken, int user_id, int id) {
            return base.Channel.Get_utokenAsync(utoken, user_id, id);
        }
    }
}
