//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobie_store.LoginService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginService.ILoginService")]
    public interface ILoginService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/LoginAdmin", ReplyAction="http://tempuri.org/ILoginService/LoginAdminResponse")]
        Mobie_store.LoginService.LoginAdminResponse LoginAdmin(Mobie_store.LoginService.LoginAdminRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/LoginAdmin", ReplyAction="http://tempuri.org/ILoginService/LoginAdminResponse")]
        System.Threading.Tasks.Task<Mobie_store.LoginService.LoginAdminResponse> LoginAdminAsync(Mobie_store.LoginService.LoginAdminRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/LoginUser", ReplyAction="http://tempuri.org/ILoginService/LoginUserResponse")]
        Mobie_store.LoginService.LoginUserResponse LoginUser(Mobie_store.LoginService.LoginUserRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/LoginUser", ReplyAction="http://tempuri.org/ILoginService/LoginUserResponse")]
        System.Threading.Tasks.Task<Mobie_store.LoginService.LoginUserResponse> LoginUserAsync(Mobie_store.LoginService.LoginUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginAdmin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        public LoginAdminRequest() {
        }
        
        public LoginAdminRequest(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginAdminResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string LoginAdminResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int id;
        
        public LoginAdminResponse() {
        }
        
        public LoginAdminResponse(string LoginAdminResult, int id) {
            this.LoginAdminResult = LoginAdminResult;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        public LoginUserRequest() {
        }
        
        public LoginUserRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string LoginUserResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int id;
        
        public LoginUserResponse() {
        }
        
        public LoginUserResponse(string LoginUserResult, int id) {
            this.LoginUserResult = LoginUserResult;
            this.id = id;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginServiceChannel : Mobie_store.LoginService.ILoginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServiceClient : System.ServiceModel.ClientBase<Mobie_store.LoginService.ILoginService>, Mobie_store.LoginService.ILoginService {
        
        public LoginServiceClient() {
        }
        
        public LoginServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mobie_store.LoginService.LoginAdminResponse Mobie_store.LoginService.ILoginService.LoginAdmin(Mobie_store.LoginService.LoginAdminRequest request) {
            return base.Channel.LoginAdmin(request);
        }
        
        public string LoginAdmin(string email, string password, out int id) {
            Mobie_store.LoginService.LoginAdminRequest inValue = new Mobie_store.LoginService.LoginAdminRequest();
            inValue.email = email;
            inValue.password = password;
            Mobie_store.LoginService.LoginAdminResponse retVal = ((Mobie_store.LoginService.ILoginService)(this)).LoginAdmin(inValue);
            id = retVal.id;
            return retVal.LoginAdminResult;
        }
        
        public System.Threading.Tasks.Task<Mobie_store.LoginService.LoginAdminResponse> LoginAdminAsync(Mobie_store.LoginService.LoginAdminRequest request) {
            return base.Channel.LoginAdminAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mobie_store.LoginService.LoginUserResponse Mobie_store.LoginService.ILoginService.LoginUser(Mobie_store.LoginService.LoginUserRequest request) {
            return base.Channel.LoginUser(request);
        }
        
        public string LoginUser(string username, string password, out int id) {
            Mobie_store.LoginService.LoginUserRequest inValue = new Mobie_store.LoginService.LoginUserRequest();
            inValue.username = username;
            inValue.password = password;
            Mobie_store.LoginService.LoginUserResponse retVal = ((Mobie_store.LoginService.ILoginService)(this)).LoginUser(inValue);
            id = retVal.id;
            return retVal.LoginUserResult;
        }
        
        public System.Threading.Tasks.Task<Mobie_store.LoginService.LoginUserResponse> LoginUserAsync(Mobie_store.LoginService.LoginUserRequest request) {
            return base.Channel.LoginUserAsync(request);
        }
    }
}
