//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobie_store.AddService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AddService.IAddService")]
    public interface IAddService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/ID_Return", ReplyAction="http://tempuri.org/IAddService/ID_ReturnResponse")]
        int ID_Return(string nametable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/ID_Return", ReplyAction="http://tempuri.org/IAddService/ID_ReturnResponse")]
        System.Threading.Tasks.Task<int> ID_ReturnAsync(string nametable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/Add_admin", ReplyAction="http://tempuri.org/IAddService/Add_adminResponse")]
        string Add_admin(string token, int admin_id, int id, string _username, string _pwd, string _email, string _address, string _phone, System.Nullable<int> _level, string _image, string _fullname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/Add_admin", ReplyAction="http://tempuri.org/IAddService/Add_adminResponse")]
        System.Threading.Tasks.Task<string> Add_adminAsync(string token, int admin_id, int id, string _username, string _pwd, string _email, string _address, string _phone, System.Nullable<int> _level, string _image, string _fullname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/Add_category", ReplyAction="http://tempuri.org/IAddService/Add_categoryResponse")]
        string Add_category(string token, int admin_id, int id, string _name, string _description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/Add_category", ReplyAction="http://tempuri.org/IAddService/Add_categoryResponse")]
        System.Threading.Tasks.Task<string> Add_categoryAsync(string token, int admin_id, int id, string _name, string _description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/Add_comment", ReplyAction="http://tempuri.org/IAddService/Add_commentResponse")]
        string Add_comment(string utoken, int _user_id, int id, System.Nullable<int> _product_id, string _comments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/Add_comment", ReplyAction="http://tempuri.org/IAddService/Add_commentResponse")]
        System.Threading.Tasks.Task<string> Add_commentAsync(string utoken, int _user_id, int id, System.Nullable<int> _product_id, string _comments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/Add_discount", ReplyAction="http://tempuri.org/IAddService/Add_discountResponse")]
        string Add_discount(string token, int admin_id, int id, string _value, string _name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/Add_discount", ReplyAction="http://tempuri.org/IAddService/Add_discountResponse")]
        System.Threading.Tasks.Task<string> Add_discountAsync(string token, int admin_id, int id, string _value, string _name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/Add_image", ReplyAction="http://tempuri.org/IAddService/Add_imageResponse")]
        string Add_image(string token, int admin_id, int id, string _url, System.Nullable<int> _product_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/Add_image", ReplyAction="http://tempuri.org/IAddService/Add_imageResponse")]
        System.Threading.Tasks.Task<string> Add_imageAsync(string token, int admin_id, int id, string _url, System.Nullable<int> _product_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/Add_order", ReplyAction="http://tempuri.org/IAddService/Add_orderResponse")]
        string Add_order(string utoken, int _user_id, int id, string _total_money, string _date_create, string _method);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/Add_order", ReplyAction="http://tempuri.org/IAddService/Add_orderResponse")]
        System.Threading.Tasks.Task<string> Add_orderAsync(string utoken, int _user_id, int id, string _total_money, string _date_create, string _method);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/Add_order_detail", ReplyAction="http://tempuri.org/IAddService/Add_order_detailResponse")]
        string Add_order_detail(string utoken, int _user_id, int _order_id, int _product_id, int _quantity, int _money);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/Add_order_detail", ReplyAction="http://tempuri.org/IAddService/Add_order_detailResponse")]
        System.Threading.Tasks.Task<string> Add_order_detailAsync(string utoken, int _user_id, int _order_id, int _product_id, int _quantity, int _money);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/Add_post", ReplyAction="http://tempuri.org/IAddService/Add_postResponse")]
        string Add_post(string token, int admin_id, int id, System.Nullable<int> _product_id, string _name, string _descripton);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/Add_post", ReplyAction="http://tempuri.org/IAddService/Add_postResponse")]
        System.Threading.Tasks.Task<string> Add_postAsync(string token, int admin_id, int id, System.Nullable<int> _product_id, string _name, string _descripton);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/Add_product", ReplyAction="http://tempuri.org/IAddService/Add_productResponse")]
        string Add_product(
                    string token, 
                    int admin_id, 
                    int id, 
                    string _sku, 
                    string _name, 
                    string _price, 
                    string _Ghz, 
                    string _color, 
                    string _sensor, 
                    string _cpu, 
                    string _ram, 
                    string _storage, 
                    string _camera_front, 
                    string _camera_rear, 
                    string _battery, 
                    string _display, 
                    string _sim, 
                    string _status, 
                    System.Nullable<int> _activate, 
                    System.Nullable<int> _product_cate_id, 
                    System.Nullable<int> _discount_id, 
                    string _image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/Add_product", ReplyAction="http://tempuri.org/IAddService/Add_productResponse")]
        System.Threading.Tasks.Task<string> Add_productAsync(
                    string token, 
                    int admin_id, 
                    int id, 
                    string _sku, 
                    string _name, 
                    string _price, 
                    string _Ghz, 
                    string _color, 
                    string _sensor, 
                    string _cpu, 
                    string _ram, 
                    string _storage, 
                    string _camera_front, 
                    string _camera_rear, 
                    string _battery, 
                    string _display, 
                    string _sim, 
                    string _status, 
                    System.Nullable<int> _activate, 
                    System.Nullable<int> _product_cate_id, 
                    System.Nullable<int> _discount_id, 
                    string _image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/Add_review", ReplyAction="http://tempuri.org/IAddService/Add_reviewResponse")]
        string Add_review(string utoken, int _user_id, int id, System.Nullable<int> _product_id, string _reviews);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/Add_review", ReplyAction="http://tempuri.org/IAddService/Add_reviewResponse")]
        System.Threading.Tasks.Task<string> Add_reviewAsync(string utoken, int _user_id, int id, System.Nullable<int> _product_id, string _reviews);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/Add_user", ReplyAction="http://tempuri.org/IAddService/Add_userResponse")]
        string Add_user(int id, string _username, string _fullname, string _pwd, string _email, string _address, string _phone, string _image, System.Nullable<int> _activated);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/Add_user", ReplyAction="http://tempuri.org/IAddService/Add_userResponse")]
        System.Threading.Tasks.Task<string> Add_userAsync(int id, string _username, string _fullname, string _pwd, string _email, string _address, string _phone, string _image, System.Nullable<int> _activated);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAddServiceChannel : Mobie_store.AddService.IAddService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddServiceClient : System.ServiceModel.ClientBase<Mobie_store.AddService.IAddService>, Mobie_store.AddService.IAddService {
        
        public AddServiceClient() {
        }
        
        public AddServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ID_Return(string nametable) {
            return base.Channel.ID_Return(nametable);
        }
        
        public System.Threading.Tasks.Task<int> ID_ReturnAsync(string nametable) {
            return base.Channel.ID_ReturnAsync(nametable);
        }
        
        public string Add_admin(string token, int admin_id, int id, string _username, string _pwd, string _email, string _address, string _phone, System.Nullable<int> _level, string _image, string _fullname) {
            return base.Channel.Add_admin(token, admin_id, id, _username, _pwd, _email, _address, _phone, _level, _image, _fullname);
        }
        
        public System.Threading.Tasks.Task<string> Add_adminAsync(string token, int admin_id, int id, string _username, string _pwd, string _email, string _address, string _phone, System.Nullable<int> _level, string _image, string _fullname) {
            return base.Channel.Add_adminAsync(token, admin_id, id, _username, _pwd, _email, _address, _phone, _level, _image, _fullname);
        }
        
        public string Add_category(string token, int admin_id, int id, string _name, string _description) {
            return base.Channel.Add_category(token, admin_id, id, _name, _description);
        }
        
        public System.Threading.Tasks.Task<string> Add_categoryAsync(string token, int admin_id, int id, string _name, string _description) {
            return base.Channel.Add_categoryAsync(token, admin_id, id, _name, _description);
        }
        
        public string Add_comment(string utoken, int _user_id, int id, System.Nullable<int> _product_id, string _comments) {
            return base.Channel.Add_comment(utoken, _user_id, id, _product_id, _comments);
        }
        
        public System.Threading.Tasks.Task<string> Add_commentAsync(string utoken, int _user_id, int id, System.Nullable<int> _product_id, string _comments) {
            return base.Channel.Add_commentAsync(utoken, _user_id, id, _product_id, _comments);
        }
        
        public string Add_discount(string token, int admin_id, int id, string _value, string _name) {
            return base.Channel.Add_discount(token, admin_id, id, _value, _name);
        }
        
        public System.Threading.Tasks.Task<string> Add_discountAsync(string token, int admin_id, int id, string _value, string _name) {
            return base.Channel.Add_discountAsync(token, admin_id, id, _value, _name);
        }
        
        public string Add_image(string token, int admin_id, int id, string _url, System.Nullable<int> _product_id) {
            return base.Channel.Add_image(token, admin_id, id, _url, _product_id);
        }
        
        public System.Threading.Tasks.Task<string> Add_imageAsync(string token, int admin_id, int id, string _url, System.Nullable<int> _product_id) {
            return base.Channel.Add_imageAsync(token, admin_id, id, _url, _product_id);
        }
        
        public string Add_order(string utoken, int _user_id, int id, string _total_money, string _date_create, string _method) {
            return base.Channel.Add_order(utoken, _user_id, id, _total_money, _date_create, _method);
        }
        
        public System.Threading.Tasks.Task<string> Add_orderAsync(string utoken, int _user_id, int id, string _total_money, string _date_create, string _method) {
            return base.Channel.Add_orderAsync(utoken, _user_id, id, _total_money, _date_create, _method);
        }
        
        public string Add_order_detail(string utoken, int _user_id, int _order_id, int _product_id, int _quantity, int _money) {
            return base.Channel.Add_order_detail(utoken, _user_id, _order_id, _product_id, _quantity, _money);
        }
        
        public System.Threading.Tasks.Task<string> Add_order_detailAsync(string utoken, int _user_id, int _order_id, int _product_id, int _quantity, int _money) {
            return base.Channel.Add_order_detailAsync(utoken, _user_id, _order_id, _product_id, _quantity, _money);
        }
        
        public string Add_post(string token, int admin_id, int id, System.Nullable<int> _product_id, string _name, string _descripton) {
            return base.Channel.Add_post(token, admin_id, id, _product_id, _name, _descripton);
        }
        
        public System.Threading.Tasks.Task<string> Add_postAsync(string token, int admin_id, int id, System.Nullable<int> _product_id, string _name, string _descripton) {
            return base.Channel.Add_postAsync(token, admin_id, id, _product_id, _name, _descripton);
        }
        
        public string Add_product(
                    string token, 
                    int admin_id, 
                    int id, 
                    string _sku, 
                    string _name, 
                    string _price, 
                    string _Ghz, 
                    string _color, 
                    string _sensor, 
                    string _cpu, 
                    string _ram, 
                    string _storage, 
                    string _camera_front, 
                    string _camera_rear, 
                    string _battery, 
                    string _display, 
                    string _sim, 
                    string _status, 
                    System.Nullable<int> _activate, 
                    System.Nullable<int> _product_cate_id, 
                    System.Nullable<int> _discount_id, 
                    string _image) {
            return base.Channel.Add_product(token, admin_id, id, _sku, _name, _price, _Ghz, _color, _sensor, _cpu, _ram, _storage, _camera_front, _camera_rear, _battery, _display, _sim, _status, _activate, _product_cate_id, _discount_id, _image);
        }
        
        public System.Threading.Tasks.Task<string> Add_productAsync(
                    string token, 
                    int admin_id, 
                    int id, 
                    string _sku, 
                    string _name, 
                    string _price, 
                    string _Ghz, 
                    string _color, 
                    string _sensor, 
                    string _cpu, 
                    string _ram, 
                    string _storage, 
                    string _camera_front, 
                    string _camera_rear, 
                    string _battery, 
                    string _display, 
                    string _sim, 
                    string _status, 
                    System.Nullable<int> _activate, 
                    System.Nullable<int> _product_cate_id, 
                    System.Nullable<int> _discount_id, 
                    string _image) {
            return base.Channel.Add_productAsync(token, admin_id, id, _sku, _name, _price, _Ghz, _color, _sensor, _cpu, _ram, _storage, _camera_front, _camera_rear, _battery, _display, _sim, _status, _activate, _product_cate_id, _discount_id, _image);
        }
        
        public string Add_review(string utoken, int _user_id, int id, System.Nullable<int> _product_id, string _reviews) {
            return base.Channel.Add_review(utoken, _user_id, id, _product_id, _reviews);
        }
        
        public System.Threading.Tasks.Task<string> Add_reviewAsync(string utoken, int _user_id, int id, System.Nullable<int> _product_id, string _reviews) {
            return base.Channel.Add_reviewAsync(utoken, _user_id, id, _product_id, _reviews);
        }
        
        public string Add_user(int id, string _username, string _fullname, string _pwd, string _email, string _address, string _phone, string _image, System.Nullable<int> _activated) {
            return base.Channel.Add_user(id, _username, _fullname, _pwd, _email, _address, _phone, _image, _activated);
        }
        
        public System.Threading.Tasks.Task<string> Add_userAsync(int id, string _username, string _fullname, string _pwd, string _email, string _address, string _phone, string _image, System.Nullable<int> _activated) {
            return base.Channel.Add_userAsync(id, _username, _fullname, _pwd, _email, _address, _phone, _image, _activated);
        }
    }
}
